import * as THREE from 'three'
import './style.css'
const app=document.querySelector('#app'),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;app.appendChild(renderer.domElement)
const scene=new THREE.Scene();scene.background=new THREE.Color(0x08090b);const camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.1,100);camera.position.z=18;const root=new THREE.Group();scene.add(root)
const mat=()=>new THREE.MeshPhysicalMaterial({color:0xe5231f,roughness:.3,metalness:.01,clearcoat:.55,clearcoatRoughness:.2})
const specs=[['A','PIQUANTS','spikes'],['B','CORAIL','coral'],['C','VENTOUSES','suckers'],['D','HEXAGONES EXTRUDÉS','hex'],['E','TENTACULES','tentacles'],['F','POMPONS','pompons'],['G','AIGUILLES','needles'],['H','NODULES ALIEN','nodules']]
const fract=x=>x-Math.floor(x),hash=(x,y,z)=>fract(Math.sin(x*127.1+y*311.7+z*74.7)*43758.5453)
function fibDir(i,n){const y=1-(i/(n-1))*2,r=Math.sqrt(Math.max(0,1-y*y)),a=Math.PI*(3-Math.sqrt(5))*i;return new THREE.Vector3(Math.cos(a)*r,y,Math.sin(a)*r)}
function base(){return new THREE.Mesh(new THREE.SphereGeometry(1.04,64,48),mat())}
function coneOn(group,dir,len=.42,r=.075){const g=new THREE.ConeGeometry(r,len,8),m=new THREE.Mesh(g,mat());m.position.copy(dir).multiplyScalar(1.04+len/2);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir);group.add(m)}
function ballOn(group,dir,r=.12,dist=1.08){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(r,2),mat());m.position.copy(dir).multiplyScalar(dist);group.add(m)}
function tube(group,dir,len=.55,r=.045,wave=.12){const side=new THREE.Vector3(-dir.z,0,dir.x);if(side.lengthSq()<.01)side.set(1,0,0);side.normalize();const pts=[];for(let j=0;j<7;j++){const t=j/6;pts.push(dir.clone().multiplyScalar(1.0+len*t).addScaledVector(side,Math.sin(t*Math.PI*1.4)*wave*t))}const curve=new THREE.CatmullRomCurve3(pts),m=new THREE.Mesh(new THREE.TubeGeometry(curve,16,r,7,false),mat());group.add(m)}
function make(kind){const g=new THREE.Group();g.add(base());if(kind==='spikes'){for(let i=0;i<72;i++)coneOn(g,fibDir(i,72),.34+(i%5)*.035,.055)}else if(kind==='coral'){for(let i=0;i<34;i++){const d=fibDir(i,34);tube(g,d,.3+(i%4)*.07,.055,.07);if(i%3===0)ballOn(g,d,.095,1.36)}}else if(kind==='suckers'){for(let i=0;i<48;i++){const d=fibDir(i,48),tor=new THREE.Mesh(new THREE.TorusGeometry(.09,.035,8,16),mat());tor.position.copy(d).multiplyScalar(1.075);tor.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),d);g.add(tor)}}else if(kind==='hex'){for(let i=0;i<55;i++){const d=fibDir(i,55),c=new THREE.Mesh(new THREE.CylinderGeometry(.12,.12,.12,6),mat());c.position.copy(d).multiplyScalar(1.08);c.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d);g.add(c)}}else if(kind==='tentacles'){for(let i=0;i<22;i++)tube(g,fibDir(i,22),.72+(i%4)*.08,.06,.18)}else if(kind==='pompons'){for(let i=0;i<80;i++)ballOn(g,fibDir(i,80),.105+(i%3)*.018,1.08)}else if(kind==='needles'){for(let i=0;i<120;i++)coneOn(g,fibDir(i,120),.48+(i%7)*.025,.025)}else{for(let i=0;i<46;i++){const d=fibDir(i,46),r=.08+.075*hash(i,2,7);ballOn(g,d,r,1.03+r*.45)}}return g}
const xs=[-4.5,-1.5,1.5,4.5],ys=[2.15,-2.15],meshes=[];specs.forEach((s,i)=>{const m=make(s[2]);m.position.set(xs[i%4],ys[Math.floor(i/4)],0);root.add(m);meshes.push(m)})
scene.add(new THREE.HemisphereLight(0xffffff,0x111318,1.5));const key=new THREE.DirectionalLight(0xffffff,4);key.position.set(6,8,10);scene.add(key);const rim=new THREE.PointLight(0xff3020,2.2,40);rim.position.set(-8,-2,5);scene.add(rim)
const title=document.createElement('div');title.innerHTML='<b>ENTITY — 8 TEXTURES EXTRAVAGANTES</b><span>Méthodes géométriques existantes · sélection A → H</span>';Object.assign(title.style,{position:'fixed',top:'18px',left:'50%',transform:'translateX(-50%)',color:'#fff',font:'14px Arial',letterSpacing:'.12em',textAlign:'center'});title.querySelector('span').style.cssText='display:block;margin-top:6px;font-size:10px;opacity:.55';document.body.appendChild(title)
const labels=[];specs.forEach(s=>{const d=document.createElement('div');d.innerHTML=`<b>${s[0]}</b><span>${s[1]}</span>`;Object.assign(d.style,{position:'fixed',color:'#fff',font:'10px Arial',textAlign:'center',transform:'translate(-50%,0)',whiteSpace:'nowrap'});d.querySelector('span').style.cssText='display:block;margin-top:3px;font-size:9px;opacity:.65';document.body.appendChild(d);labels.push(d)})
const v3=new THREE.Vector3(),clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04);meshes.forEach((m,i)=>{m.rotation.y+=dt*(.1+i*.008);m.rotation.x+=dt*.02;v3.copy(m.position).add(new THREE.Vector3(0,-1.62,0)).project(camera);labels[i].style.left=`${(v3.x*.5+.5)*innerWidth}px`;labels[i].style.top=`${(-v3.y*.5+.5)*innerHeight}px`});renderer.render(scene,camera)}animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)})